name: Build APK

on:
  push:
    paths:
      - '**.py'
      - 'buildozer.spec'
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          
      - name: Cache buildozer global directory
        uses: actions/cache@v3
        with:
          path: ~/.buildozer
          key: ${{ runner.os }}-buildozer-${{ hashFiles('**/buildozer.spec') }}
          restore-keys: |
            ${{ runner.os }}-buildozer-
            
      - name: Cache buildozer dependencies
        uses: actions/cache@v3
        with:
          path: .buildozer
          key: ${{ runner.os }}-buildozer-deps-${{ hashFiles('**/buildozer.spec') }}
          restore-keys: |
            ${{ runner.os }}-buildozer-deps-
            
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            ccache \
            git \
            libffi-dev \
            libssl-dev \
            libxml2-dev \
            libxslt-dev \
            libjpeg-dev \
            libpng-dev \
            zlib1g-dev \
            libncurses5:i386 \
            libstdc++6:i386 \
            libgtk2.0-dev \
            libpangocairo-1.0-0 \
            libatk1.0-dev \
            libcairo-gobject2 \
            libgtk-3-dev \
            libgdk-pixbuf2.0-dev \
            unzip \
            zip \
            openjdk-17-jdk
            
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade \
            cython==0.29.34 \
            buildozer \
            kivy \
            requests
            
      - name: Initialize buildozer
        run: |
          buildozer init || true
          
      - name: Build APK
        run: |
          buildozer android debug
          
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: MMDVMHotspot-apk
          path: bin/*.apk
          
      - name: Upload build logs
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: build-logs
          path: |
            .buildozer/android/platform/build-*/**/build.log
            .buildozer/android/platform/build-*/**/gradle.log
